[package]
name = "maze_tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
enum-iterator = "2.0.0"
ratatui = "0.26.1"

[dependencies.maze_lib]
path = "../maze_lib"
